version: "3"

services:
  navidrome:
    image: deluan/navidrome
    container_name: navidrome-service
    user: 1000:984 # should be owner of volumes
    restart: unless-stopped
    environment:
      # Optional: put your config options customization here. Examples:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info  
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: ""
    volumes:
      - "data:/data"
      - "/mnt/HD1/music:/music:ro"
    networks:
      server-network:
        ipv4_address: 172.40.0.6

volumes: 
  data:

networks:
    server-network:
        external: true
        name: server-containers