version: "3"

services:
  navidrome:
    image: deluan/navidrome
    user: ${USER_ID}:${GROUP_IP}
    container_name: navidrome-service
    restart: always
    environment:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info  
      ND_SESSIONTIMEOUT: 24h
    volumes:
      - "data:/data"
      - "${MUSIC_PATH}:/music:ro"
    networks:
      net:
    ports:
      - 45330:4533

volumes: 
  data:

networks:
  net: